/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_choix (void);
GtkWidget* create_Ajoutobs (void);
GtkWidget* create_Liste (void);
GtkWidget* create_Supp (void);
GtkWidget* create_Modif (void);
GtkWidget* create_chercher_obser (void);
GtkWidget* create_stat_HF (void);
