/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_choix (void)
{
  GtkWidget *choix;
  GtkWidget *fixed1;
  GtkWidget *AJobs;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *modifobs;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *Suppobs;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *image17;
  GtkWidget *image16;
  GtkWidget *statobs;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *Cheobs;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *Lisobs;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;

  choix = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (choix), _("Choix"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (choix), fixed1);

  AJobs = gtk_button_new ();
  gtk_widget_show (AJobs);
  gtk_fixed_put (GTK_FIXED (fixed1), AJobs, 168, 144);
  gtk_widget_set_size_request (AJobs, 362, 48);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (AJobs), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter un observateur"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  modifobs = gtk_button_new ();
  gtk_widget_show (modifobs);
  gtk_fixed_put (GTK_FIXED (fixed1), modifobs, 168, 232);
  gtk_widget_set_size_request (modifobs, 360, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (modifobs), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Modifier un observateur"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  Suppobs = gtk_button_new ();
  gtk_widget_show (Suppobs);
  gtk_fixed_put (GTK_FIXED (fixed1), Suppobs, 168, 312);
  gtk_widget_set_size_request (Suppobs, 360, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (Suppobs), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Supprimer un observateur"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  image17 = create_pixmap (choix, "admin.png");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed1), image17, 0, 0);
  gtk_widget_set_size_request (image17, 712, 64);

  image16 = create_pixmap (choix, "266366478_4576459329133260_7737124276348460294_n.png");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed1), image16, 0, 656);
  gtk_widget_set_size_request (image16, 712, 40);

  statobs = gtk_button_new ();
  gtk_widget_show (statobs);
  gtk_fixed_put (GTK_FIXED (fixed1), statobs, 168, 592);
  gtk_widget_set_size_request (statobs, 360, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (statobs), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Statistiques"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  Cheobs = gtk_button_new ();
  gtk_widget_show (Cheobs);
  gtk_fixed_put (GTK_FIXED (fixed1), Cheobs, 168, 504);
  gtk_widget_set_size_request (Cheobs, 360, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (Cheobs), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Chercher un observateur"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  Lisobs = gtk_button_new ();
  gtk_widget_show (Lisobs);
  gtk_fixed_put (GTK_FIXED (fixed1), Lisobs, 168, 408);
  gtk_widget_set_size_request (Lisobs, 360, 48);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (Lisobs), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Liste des observateurs"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) AJobs, "clicked",
                    G_CALLBACK (on_AJobs_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifobs, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) Suppobs, "clicked",
                    G_CALLBACK (on_Suppobs_clicked),
                    NULL);
  g_signal_connect ((gpointer) statobs, "clicked",
                    G_CALLBACK (on_statobs_clicked),
                    NULL);
  g_signal_connect ((gpointer) Cheobs, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) Lisobs, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (choix, choix, "choix");
  GLADE_HOOKUP_OBJECT (choix, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (choix, AJobs, "AJobs");
  GLADE_HOOKUP_OBJECT (choix, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (choix, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (choix, image1, "image1");
  GLADE_HOOKUP_OBJECT (choix, label1, "label1");
  GLADE_HOOKUP_OBJECT (choix, modifobs, "modifobs");
  GLADE_HOOKUP_OBJECT (choix, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (choix, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (choix, image2, "image2");
  GLADE_HOOKUP_OBJECT (choix, label2, "label2");
  GLADE_HOOKUP_OBJECT (choix, Suppobs, "Suppobs");
  GLADE_HOOKUP_OBJECT (choix, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (choix, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (choix, image3, "image3");
  GLADE_HOOKUP_OBJECT (choix, label3, "label3");
  GLADE_HOOKUP_OBJECT (choix, image17, "image17");
  GLADE_HOOKUP_OBJECT (choix, image16, "image16");
  GLADE_HOOKUP_OBJECT (choix, statobs, "statobs");
  GLADE_HOOKUP_OBJECT (choix, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (choix, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (choix, image6, "image6");
  GLADE_HOOKUP_OBJECT (choix, label6, "label6");
  GLADE_HOOKUP_OBJECT (choix, Cheobs, "Cheobs");
  GLADE_HOOKUP_OBJECT (choix, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (choix, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (choix, image5, "image5");
  GLADE_HOOKUP_OBJECT (choix, label5, "label5");
  GLADE_HOOKUP_OBJECT (choix, Lisobs, "Lisobs");
  GLADE_HOOKUP_OBJECT (choix, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (choix, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (choix, image4, "image4");
  GLADE_HOOKUP_OBJECT (choix, label4, "label4");

  return choix;
}

GtkWidget*
create_Ajoutobs (void)
{
  GtkWidget *Ajoutobs;
  GtkWidget *fixed2;
  GtkWidget *label1;
  GtkWidget *label9;
  GtkWidget *label13;
  GtkObject *spjour_adj;
  GtkWidget *spjour;
  GtkWidget *label14;
  GtkObject *spmois_adj;
  GtkWidget *spmois;
  GtkWidget *label16;
  GtkWidget *label15;
  GtkObject *spanne_adj;
  GtkWidget *spanne;
  GtkWidget *label10;
  GtkWidget *label8;
  GtkWidget *ajnomobs;
  GtkWidget *ajprenomobs;
  GtkWidget *entry3;
  GtkWidget *ajcinobs;
  GtkWidget *label12;
  GtkWidget *label11;
  GtkWidget *ajtobs;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label17;
  GtkWidget *rdobs2;
  GSList *rdobs2_group = NULL;
  GtkWidget *cbnatio;
  GtkObject *bureau_M_adj;
  GtkWidget *bureau_M;
  GtkWidget *rdobs;
  GtkWidget *retour_choix;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label29;

  Ajoutobs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajoutobs), _("Ajouter un observateur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Ajoutobs), fixed2);

  label1 = gtk_label_new (_("Nom"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed2), label1, 40, 88);
  gtk_widget_set_size_request (label1, 72, 32);

  label9 = gtk_label_new (_("CIN"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 48, 184);
  gtk_widget_set_size_request (label9, 56, 32);

  label13 = gtk_label_new (_("Date d'ajout"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 344, 80);
  gtk_widget_set_size_request (label13, 96, 40);

  spjour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spjour = gtk_spin_button_new (GTK_ADJUSTMENT (spjour_adj), 1, 0);
  gtk_widget_show (spjour);
  gtk_fixed_put (GTK_FIXED (fixed2), spjour, 400, 136);
  gtk_widget_set_size_request (spjour, 60, 27);

  label14 = gtk_label_new (_("Jour"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 352, 136);
  gtk_widget_set_size_request (label14, 48, 24);

  spmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spmois = gtk_spin_button_new (GTK_ADJUSTMENT (spmois_adj), 1, 0);
  gtk_widget_show (spmois);
  gtk_fixed_put (GTK_FIXED (fixed2), spmois, 512, 136);
  gtk_widget_set_size_request (spmois, 60, 27);

  label16 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 576, 136);
  gtk_widget_set_size_request (label16, 56, 24);

  label15 = gtk_label_new (_("Mois"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 464, 136);
  gtk_widget_set_size_request (label15, 48, 24);

  spanne_adj = gtk_adjustment_new (1, 2022, 2023, 1, 10, 10);
  spanne = gtk_spin_button_new (GTK_ADJUSTMENT (spanne_adj), 1, 0);
  gtk_widget_show (spanne);
  gtk_fixed_put (GTK_FIXED (fixed2), spanne, 632, 136);
  gtk_widget_set_size_request (spanne, 60, 27);

  label10 = gtk_label_new (_("Nationalite"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 320, 216);
  gtk_widget_set_size_request (label10, 96, 32);

  label8 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 48, 128);
  gtk_widget_set_size_request (label8, 72, 40);

  ajnomobs = gtk_entry_new ();
  gtk_widget_show (ajnomobs);
  gtk_fixed_put (GTK_FIXED (fixed2), ajnomobs, 120, 88);
  gtk_widget_set_size_request (ajnomobs, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajnomobs), 8226);

  ajprenomobs = gtk_entry_new ();
  gtk_widget_show (ajprenomobs);
  gtk_fixed_put (GTK_FIXED (fixed2), ajprenomobs, 120, 136);
  gtk_widget_set_size_request (ajprenomobs, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajprenomobs), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 120, 184);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  ajcinobs = gtk_entry_new ();
  gtk_widget_show (ajcinobs);
  gtk_fixed_put (GTK_FIXED (fixed2), ajcinobs, 120, 184);
  gtk_widget_set_size_request (ajcinobs, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajcinobs), 8226);

  label12 = gtk_label_new (_("N\302\260 bureau"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 40, 344);
  gtk_widget_set_size_request (label12, 96, 48);

  label11 = gtk_label_new (_("Genre"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 72, 256);
  gtk_widget_set_size_request (label11, 80, 40);

  ajtobs = gtk_button_new ();
  gtk_widget_show (ajtobs);
  gtk_fixed_put (GTK_FIXED (fixed2), ajtobs, 360, 416);
  gtk_widget_set_size_request (ajtobs, 104, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (ajtobs), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);

  rdobs2 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (rdobs2);
  gtk_fixed_put (GTK_FIXED (fixed2), rdobs2, 160, 288);
  gtk_widget_set_size_request (rdobs2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rdobs2), rdobs2_group);
  rdobs2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rdobs2));

  cbnatio = gtk_combo_box_new_text ();
  gtk_widget_show (cbnatio);
  gtk_fixed_put (GTK_FIXED (fixed2), cbnatio, 424, 216);
  gtk_widget_set_size_request (cbnatio, 128, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbnatio), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbnatio), _("Autres"));

  bureau_M_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  bureau_M = gtk_spin_button_new (GTK_ADJUSTMENT (bureau_M_adj), 1, 0);
  gtk_widget_show (bureau_M);
  gtk_fixed_put (GTK_FIXED (fixed2), bureau_M, 160, 352);
  gtk_widget_set_size_request (bureau_M, 60, 27);

  rdobs = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (rdobs);
  gtk_fixed_put (GTK_FIXED (fixed2), rdobs, 160, 248);
  gtk_widget_set_size_request (rdobs, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rdobs), rdobs2_group);
  rdobs2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rdobs));

  retour_choix = gtk_button_new ();
  gtk_widget_show (retour_choix);
  gtk_fixed_put (GTK_FIXED (fixed2), retour_choix, 224, 416);
  gtk_widget_set_size_request (retour_choix, 96, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (retour_choix), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox13), label29, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ajtobs, "clicked",
                    G_CALLBACK (on_ajtobs_clicked),
                    NULL);
  g_signal_connect ((gpointer) rdobs2, "toggled",
                    G_CALLBACK (on_rdobs2_toggled),
                    NULL);
  g_signal_connect ((gpointer) rdobs, "toggled",
                    G_CALLBACK (on_rdobs_toggled),
                    NULL);
  g_signal_connect ((gpointer) retour_choix, "clicked",
                    G_CALLBACK (on_retour_choix_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajoutobs, Ajoutobs, "Ajoutobs");
  GLADE_HOOKUP_OBJECT (Ajoutobs, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Ajoutobs, label1, "label1");
  GLADE_HOOKUP_OBJECT (Ajoutobs, label9, "label9");
  GLADE_HOOKUP_OBJECT (Ajoutobs, label13, "label13");
  GLADE_HOOKUP_OBJECT (Ajoutobs, spjour, "spjour");
  GLADE_HOOKUP_OBJECT (Ajoutobs, label14, "label14");
  GLADE_HOOKUP_OBJECT (Ajoutobs, spmois, "spmois");
  GLADE_HOOKUP_OBJECT (Ajoutobs, label16, "label16");
  GLADE_HOOKUP_OBJECT (Ajoutobs, label15, "label15");
  GLADE_HOOKUP_OBJECT (Ajoutobs, spanne, "spanne");
  GLADE_HOOKUP_OBJECT (Ajoutobs, label10, "label10");
  GLADE_HOOKUP_OBJECT (Ajoutobs, label8, "label8");
  GLADE_HOOKUP_OBJECT (Ajoutobs, ajnomobs, "ajnomobs");
  GLADE_HOOKUP_OBJECT (Ajoutobs, ajprenomobs, "ajprenomobs");
  GLADE_HOOKUP_OBJECT (Ajoutobs, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Ajoutobs, ajcinobs, "ajcinobs");
  GLADE_HOOKUP_OBJECT (Ajoutobs, label12, "label12");
  GLADE_HOOKUP_OBJECT (Ajoutobs, label11, "label11");
  GLADE_HOOKUP_OBJECT (Ajoutobs, ajtobs, "ajtobs");
  GLADE_HOOKUP_OBJECT (Ajoutobs, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Ajoutobs, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Ajoutobs, image7, "image7");
  GLADE_HOOKUP_OBJECT (Ajoutobs, label17, "label17");
  GLADE_HOOKUP_OBJECT (Ajoutobs, rdobs2, "rdobs2");
  GLADE_HOOKUP_OBJECT (Ajoutobs, cbnatio, "cbnatio");
  GLADE_HOOKUP_OBJECT (Ajoutobs, bureau_M, "bureau_M");
  GLADE_HOOKUP_OBJECT (Ajoutobs, rdobs, "rdobs");
  GLADE_HOOKUP_OBJECT (Ajoutobs, retour_choix, "retour_choix");
  GLADE_HOOKUP_OBJECT (Ajoutobs, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Ajoutobs, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Ajoutobs, image13, "image13");
  GLADE_HOOKUP_OBJECT (Ajoutobs, label29, "label29");

  return Ajoutobs;
}

GtkWidget*
create_Liste (void)
{
  GtkWidget *Liste;
  GtkWidget *fixed3;
  GtkWidget *treeview_observateur;
  GtkWidget *retour_list_choix;
  GtkWidget *actliste;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label18;

  Liste = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Liste), _("Liste des observateurs"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Liste), fixed3);

  treeview_observateur = gtk_tree_view_new ();
  gtk_widget_show (treeview_observateur);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview_observateur, 96, 112);
  gtk_widget_set_size_request (treeview_observateur, 632, 296);

  retour_list_choix = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (retour_list_choix);
  gtk_fixed_put (GTK_FIXED (fixed3), retour_list_choix, 104, 488);
  gtk_widget_set_size_request (retour_list_choix, 232, 56);

  actliste = gtk_button_new ();
  gtk_widget_show (actliste);
  gtk_fixed_put (GTK_FIXED (fixed3), actliste, 448, 488);
  gtk_widget_set_size_request (actliste, 256, 56);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (actliste), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox8), label18, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_observateur, "row_activated",
                    G_CALLBACK (on_treeview_observateur_row_activated),
                    NULL);
  g_signal_connect ((gpointer) retour_list_choix, "clicked",
                    G_CALLBACK (on_retour_list_choix_clicked),
                    NULL);
  g_signal_connect ((gpointer) actliste, "clicked",
                    G_CALLBACK (on_actliste_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Liste, Liste, "Liste");
  GLADE_HOOKUP_OBJECT (Liste, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Liste, treeview_observateur, "treeview_observateur");
  GLADE_HOOKUP_OBJECT (Liste, retour_list_choix, "retour_list_choix");
  GLADE_HOOKUP_OBJECT (Liste, actliste, "actliste");
  GLADE_HOOKUP_OBJECT (Liste, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Liste, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Liste, image8, "image8");
  GLADE_HOOKUP_OBJECT (Liste, label18, "label18");

  return Liste;
}

GtkWidget*
create_Supp (void)
{
  GtkWidget *Supp;
  GtkWidget *fixed4;
  GtkWidget *supobscin;
  GtkWidget *deleteobs;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label21;
  GtkWidget *label19;
  GtkWidget *retour_supp_choix;

  Supp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Supp), _("Supprimer un observateur"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Supp), fixed4);

  supobscin = gtk_entry_new ();
  gtk_widget_show (supobscin);
  gtk_fixed_put (GTK_FIXED (fixed4), supobscin, 192, 48);
  gtk_widget_set_size_request (supobscin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (supobscin), 8226);

  deleteobs = gtk_button_new ();
  gtk_widget_show (deleteobs);
  gtk_fixed_put (GTK_FIXED (fixed4), deleteobs, 208, 184);
  gtk_widget_set_size_request (deleteobs, 216, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (deleteobs), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox10), label21, FALSE, FALSE, 0);

  label19 = gtk_label_new (_("CIN"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 80, 48);
  gtk_widget_set_size_request (label19, 56, 24);

  retour_supp_choix = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (retour_supp_choix);
  gtk_fixed_put (GTK_FIXED (fixed4), retour_supp_choix, 8, 184);
  gtk_widget_set_size_request (retour_supp_choix, 176, 48);

  g_signal_connect ((gpointer) deleteobs, "clicked",
                    G_CALLBACK (on_deleteobs_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_supp_choix, "clicked",
                    G_CALLBACK (on_retour_supp_choix_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supp, Supp, "Supp");
  GLADE_HOOKUP_OBJECT (Supp, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Supp, supobscin, "supobscin");
  GLADE_HOOKUP_OBJECT (Supp, deleteobs, "deleteobs");
  GLADE_HOOKUP_OBJECT (Supp, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Supp, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Supp, image10, "image10");
  GLADE_HOOKUP_OBJECT (Supp, label21, "label21");
  GLADE_HOOKUP_OBJECT (Supp, label19, "label19");
  GLADE_HOOKUP_OBJECT (Supp, retour_supp_choix, "retour_supp_choix");

  return Supp;
}

GtkWidget*
create_Modif (void)
{
  GtkWidget *Modif;
  GtkWidget *fixed5;
  GtkWidget *label22;
  GtkWidget *modifcinobs;
  GtkWidget *modnom;
  GtkWidget *modprenom;
  GtkWidget *affdataobs;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label23;
  GtkObject *jour_modifier_adj;
  GtkWidget *jour_modifier;
  GtkObject *mois_modifier_adj;
  GtkWidget *mois_modifier;
  GtkObject *annee_modifier_adj;
  GtkWidget *annee_modifier;
  GtkObject *num_bureau_adj;
  GtkWidget *num_bureau;
  GtkWidget *natio_M;
  GtkWidget *label27;
  GtkWidget *label25;
  GtkWidget *_;
  GtkWidget *verif_M;
  GtkWidget *button12;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label28;
  GtkWidget *label26;
  GtkWidget *GENRE_MO;
  GtkWidget *genre_MM;
  GtkWidget *retour_modif_choix;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label30;

  Modif = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modif), _("Modifier un observateur"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Modif), fixed5);

  label22 = gtk_label_new (_("CIN"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 48, 48);
  gtk_widget_set_size_request (label22, 80, 40);

  modifcinobs = gtk_entry_new ();
  gtk_widget_show (modifcinobs);
  gtk_fixed_put (GTK_FIXED (fixed5), modifcinobs, 120, 56);
  gtk_widget_set_size_request (modifcinobs, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modifcinobs), 8226);

  modnom = gtk_entry_new ();
  gtk_widget_show (modnom);
  gtk_fixed_put (GTK_FIXED (fixed5), modnom, 152, 208);
  gtk_widget_set_size_request (modnom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modnom), 8226);

  modprenom = gtk_entry_new ();
  gtk_widget_show (modprenom);
  gtk_fixed_put (GTK_FIXED (fixed5), modprenom, 168, 256);
  gtk_widget_set_size_request (modprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modprenom), 8226);

  affdataobs = gtk_button_new ();
  gtk_widget_show (affdataobs);
  gtk_fixed_put (GTK_FIXED (fixed5), affdataobs, 360, 48);
  gtk_widget_set_size_request (affdataobs, 208, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (affdataobs), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Afiicher les donn\303\251es"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox11), label23, FALSE, FALSE, 0);

  jour_modifier_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (jour_modifier_adj), 1, 0);
  gtk_widget_show (jour_modifier);
  gtk_fixed_put (GTK_FIXED (fixed5), jour_modifier, 112, 144);
  gtk_widget_set_size_request (jour_modifier, 60, 27);

  mois_modifier_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (mois_modifier_adj), 1, 0);
  gtk_widget_show (mois_modifier);
  gtk_fixed_put (GTK_FIXED (fixed5), mois_modifier, 208, 144);
  gtk_widget_set_size_request (mois_modifier, 60, 27);

  annee_modifier_adj = gtk_adjustment_new (1, 2022, 2023, 1, 10, 10);
  annee_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (annee_modifier_adj), 1, 0);
  gtk_widget_show (annee_modifier);
  gtk_fixed_put (GTK_FIXED (fixed5), annee_modifier, 312, 144);
  gtk_widget_set_size_request (annee_modifier, 60, 27);

  num_bureau_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  num_bureau = gtk_spin_button_new (GTK_ADJUSTMENT (num_bureau_adj), 1, 0);
  gtk_widget_show (num_bureau);
  gtk_fixed_put (GTK_FIXED (fixed5), num_bureau, 232, 392);
  gtk_widget_set_size_request (num_bureau, 60, 27);

  natio_M = gtk_entry_new ();
  gtk_widget_show (natio_M);
  gtk_fixed_put (GTK_FIXED (fixed5), natio_M, 184, 296);
  gtk_widget_set_size_request (natio_M, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (natio_M), 8226);

  label27 = gtk_label_new (_("Nationalit\303\251"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 56, 296);
  gtk_widget_set_size_request (label27, 104, 32);

  label25 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 64, 248);
  gtk_widget_set_size_request (label25, 72, 40);

  _ = gtk_label_new (_("Nom"));
  gtk_widget_show (_);
  gtk_fixed_put (GTK_FIXED (fixed5), _, 64, 200);
  gtk_widget_set_size_request (_, 72, 32);

  verif_M = gtk_label_new ("");
  gtk_widget_show (verif_M);
  gtk_fixed_put (GTK_FIXED (fixed5), verif_M, 104, 104);
  gtk_widget_set_size_request (verif_M, 232, 32);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed5), button12, 200, 432);
  gtk_widget_set_size_request (button12, 200, 48);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button12), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox12), label28, FALSE, FALSE, 0);

  label26 = gtk_label_new (_("N\302\260 bureau"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 88, 392);
  gtk_widget_set_size_request (label26, 104, 32);

  GENRE_MO = gtk_entry_new ();
  gtk_widget_show (GENRE_MO);
  gtk_fixed_put (GTK_FIXED (fixed5), GENRE_MO, 184, 344);
  gtk_widget_set_size_request (GENRE_MO, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (GENRE_MO), 8226);

  genre_MM = gtk_label_new (_("Genre"));
  gtk_widget_show (genre_MM);
  gtk_fixed_put (GTK_FIXED (fixed5), genre_MM, 80, 344);
  gtk_widget_set_size_request (genre_MM, 80, 32);

  retour_modif_choix = gtk_button_new ();
  gtk_widget_show (retour_modif_choix);
  gtk_fixed_put (GTK_FIXED (fixed5), retour_modif_choix, 424, 432);
  gtk_widget_set_size_request (retour_modif_choix, 160, 48);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (retour_modif_choix), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox14), label30, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) affdataobs, "clicked",
                    G_CALLBACK (on_affdataobs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_modif_choix, "clicked",
                    G_CALLBACK (on_retour_modif_choix_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modif, Modif, "Modif");
  GLADE_HOOKUP_OBJECT (Modif, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Modif, label22, "label22");
  GLADE_HOOKUP_OBJECT (Modif, modifcinobs, "modifcinobs");
  GLADE_HOOKUP_OBJECT (Modif, modnom, "modnom");
  GLADE_HOOKUP_OBJECT (Modif, modprenom, "modprenom");
  GLADE_HOOKUP_OBJECT (Modif, affdataobs, "affdataobs");
  GLADE_HOOKUP_OBJECT (Modif, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Modif, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Modif, image11, "image11");
  GLADE_HOOKUP_OBJECT (Modif, label23, "label23");
  GLADE_HOOKUP_OBJECT (Modif, jour_modifier, "jour_modifier");
  GLADE_HOOKUP_OBJECT (Modif, mois_modifier, "mois_modifier");
  GLADE_HOOKUP_OBJECT (Modif, annee_modifier, "annee_modifier");
  GLADE_HOOKUP_OBJECT (Modif, num_bureau, "num_bureau");
  GLADE_HOOKUP_OBJECT (Modif, natio_M, "natio_M");
  GLADE_HOOKUP_OBJECT (Modif, label27, "label27");
  GLADE_HOOKUP_OBJECT (Modif, label25, "label25");
  GLADE_HOOKUP_OBJECT (Modif, _, "_");
  GLADE_HOOKUP_OBJECT (Modif, verif_M, "verif_M");
  GLADE_HOOKUP_OBJECT (Modif, button12, "button12");
  GLADE_HOOKUP_OBJECT (Modif, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Modif, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Modif, image12, "image12");
  GLADE_HOOKUP_OBJECT (Modif, label28, "label28");
  GLADE_HOOKUP_OBJECT (Modif, label26, "label26");
  GLADE_HOOKUP_OBJECT (Modif, GENRE_MO, "GENRE_MO");
  GLADE_HOOKUP_OBJECT (Modif, genre_MM, "genre_MM");
  GLADE_HOOKUP_OBJECT (Modif, retour_modif_choix, "retour_modif_choix");
  GLADE_HOOKUP_OBJECT (Modif, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Modif, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Modif, image14, "image14");
  GLADE_HOOKUP_OBJECT (Modif, label30, "label30");

  return Modif;
}

GtkWidget*
create_chercher_obser (void)
{
  GtkWidget *chercher_obser;
  GtkWidget *fixed6;
  GtkWidget *chercher_input;
  GtkWidget *label_M;
  GtkWidget *calendar1;
  GtkWidget *output_C7;
  GtkWidget *retour_choix_chercher_ob;
  GtkWidget *button17_Mchercher;
  GtkWidget *get_cal;
  GtkWidget *cal_output;
  GtkWidget *output_C6;
  GtkWidget *output_C5;
  GtkWidget *output_C4;
  GtkWidget *output_C3;
  GtkWidget *output_C1;
  GtkWidget *output_C2;
  GtkWidget *treeview_filter;
  GtkWidget *etran_filter;
  GtkWidget *local_filter;
  GtkWidget *filter_filter;

  chercher_obser = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (chercher_obser), _("window2"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (chercher_obser), fixed6);

  chercher_input = gtk_entry_new ();
  gtk_widget_show (chercher_input);
  gtk_fixed_put (GTK_FIXED (fixed6), chercher_input, 208, 16);
  gtk_widget_set_size_request (chercher_input, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (chercher_input), 8226);

  label_M = gtk_label_new (_("cin"));
  gtk_widget_show (label_M);
  gtk_fixed_put (GTK_FIXED (fixed6), label_M, 72, 24);
  gtk_widget_set_size_request (label_M, 88, 24);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed6), calendar1, 672, 24);
  gtk_widget_set_size_request (calendar1, 253, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  output_C7 = gtk_label_new ("");
  gtk_widget_show (output_C7);
  gtk_fixed_put (GTK_FIXED (fixed6), output_C7, 368, 16);
  gtk_widget_set_size_request (output_C7, 248, 32);

  retour_choix_chercher_ob = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (retour_choix_chercher_ob);
  gtk_fixed_put (GTK_FIXED (fixed6), retour_choix_chercher_ob, 0, 560);
  gtk_widget_set_size_request (retour_choix_chercher_ob, 128, 48);

  button17_Mchercher = gtk_button_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (button17_Mchercher);
  gtk_fixed_put (GTK_FIXED (fixed6), button17_Mchercher, 208, 56);
  gtk_widget_set_size_request (button17_Mchercher, 144, 48);

  get_cal = gtk_button_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (get_cal);
  gtk_fixed_put (GTK_FIXED (fixed6), get_cal, 736, 264);
  gtk_widget_set_size_request (get_cal, 152, 48);

  cal_output = gtk_label_new ("");
  gtk_widget_show (cal_output);
  gtk_fixed_put (GTK_FIXED (fixed6), cal_output, 560, 368);
  gtk_widget_set_size_request (cal_output, 504, 80);

  output_C6 = gtk_label_new ("");
  gtk_widget_show (output_C6);
  gtk_fixed_put (GTK_FIXED (fixed6), output_C6, 192, 384);
  gtk_widget_set_size_request (output_C6, 96, 32);

  output_C5 = gtk_label_new ("");
  gtk_widget_show (output_C5);
  gtk_fixed_put (GTK_FIXED (fixed6), output_C5, 144, 328);
  gtk_widget_set_size_request (output_C5, 184, 40);

  output_C4 = gtk_label_new ("");
  gtk_widget_show (output_C4);
  gtk_fixed_put (GTK_FIXED (fixed6), output_C4, 136, 288);
  gtk_widget_set_size_request (output_C4, 208, 40);

  output_C3 = gtk_label_new ("");
  gtk_widget_show (output_C3);
  gtk_fixed_put (GTK_FIXED (fixed6), output_C3, 136, 240);
  gtk_widget_set_size_request (output_C3, 200, 40);

  output_C1 = gtk_label_new ("");
  gtk_widget_show (output_C1);
  gtk_fixed_put (GTK_FIXED (fixed6), output_C1, 128, 192);
  gtk_widget_set_size_request (output_C1, 216, 32);

  output_C2 = gtk_label_new ("");
  gtk_widget_show (output_C2);
  gtk_fixed_put (GTK_FIXED (fixed6), output_C2, 120, 136);
  gtk_widget_set_size_request (output_C2, 216, 32);

  treeview_filter = gtk_tree_view_new ();
  gtk_widget_show (treeview_filter);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview_filter, 1056, 24);
  gtk_widget_set_size_request (treeview_filter, 464, 208);

  etran_filter = gtk_check_button_new_with_mnemonic (_("Etrang\303\251res"));
  gtk_widget_show (etran_filter);
  gtk_fixed_put (GTK_FIXED (fixed6), etran_filter, 1112, 296);
  gtk_widget_set_size_request (etran_filter, 176, 32);

  local_filter = gtk_check_button_new_with_mnemonic (_("Locaux"));
  gtk_widget_show (local_filter);
  gtk_fixed_put (GTK_FIXED (fixed6), local_filter, 1304, 296);
  gtk_widget_set_size_request (local_filter, 168, 32);

  filter_filter = gtk_button_new_with_mnemonic (_("button14"));
  gtk_widget_show (filter_filter);
  gtk_fixed_put (GTK_FIXED (fixed6), filter_filter, 1216, 344);
  gtk_widget_set_size_request (filter_filter, 120, 48);

  g_signal_connect ((gpointer) retour_choix_chercher_ob, "clicked",
                    G_CALLBACK (on_retour_choix_chercher_ob_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17_Mchercher, "clicked",
                    G_CALLBACK (on_button17_Mchercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) get_cal, "clicked",
                    G_CALLBACK (on_get_cal_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_filter, "row_activated",
                    G_CALLBACK (on_treeview_filter_row_activated),
                    NULL);
  g_signal_connect ((gpointer) etran_filter, "toggled",
                    G_CALLBACK (on_etran_filter_toggled),
                    NULL);
  g_signal_connect ((gpointer) local_filter, "toggled",
                    G_CALLBACK (on_local_filter_toggled),
                    NULL);
  g_signal_connect ((gpointer) filter_filter, "clicked",
                    G_CALLBACK (on_filter_filter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (chercher_obser, chercher_obser, "chercher_obser");
  GLADE_HOOKUP_OBJECT (chercher_obser, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (chercher_obser, chercher_input, "chercher_input");
  GLADE_HOOKUP_OBJECT (chercher_obser, label_M, "label_M");
  GLADE_HOOKUP_OBJECT (chercher_obser, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (chercher_obser, output_C7, "output_C7");
  GLADE_HOOKUP_OBJECT (chercher_obser, retour_choix_chercher_ob, "retour_choix_chercher_ob");
  GLADE_HOOKUP_OBJECT (chercher_obser, button17_Mchercher, "button17_Mchercher");
  GLADE_HOOKUP_OBJECT (chercher_obser, get_cal, "get_cal");
  GLADE_HOOKUP_OBJECT (chercher_obser, cal_output, "cal_output");
  GLADE_HOOKUP_OBJECT (chercher_obser, output_C6, "output_C6");
  GLADE_HOOKUP_OBJECT (chercher_obser, output_C5, "output_C5");
  GLADE_HOOKUP_OBJECT (chercher_obser, output_C4, "output_C4");
  GLADE_HOOKUP_OBJECT (chercher_obser, output_C3, "output_C3");
  GLADE_HOOKUP_OBJECT (chercher_obser, output_C1, "output_C1");
  GLADE_HOOKUP_OBJECT (chercher_obser, output_C2, "output_C2");
  GLADE_HOOKUP_OBJECT (chercher_obser, treeview_filter, "treeview_filter");
  GLADE_HOOKUP_OBJECT (chercher_obser, etran_filter, "etran_filter");
  GLADE_HOOKUP_OBJECT (chercher_obser, local_filter, "local_filter");
  GLADE_HOOKUP_OBJECT (chercher_obser, filter_filter, "filter_filter");

  return chercher_obser;
}

GtkWidget*
create_stat_HF (void)
{
  GtkWidget *stat_HF;
  GtkWidget *fixed7;
  GtkWidget *output_calucul;
  GtkWidget *calcul_femme;
  GtkWidget *calcul_homme;
  GtkWidget *output_fff;
  GtkWidget *retour_stat_choix;

  stat_HF = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (stat_HF, 448, 556);
  gtk_window_set_title (GTK_WINDOW (stat_HF), _("stat"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (stat_HF), fixed7);
  gtk_widget_set_size_request (fixed7, 0, 448);

  output_calucul = gtk_label_new ("");
  gtk_widget_show (output_calucul);
  gtk_fixed_put (GTK_FIXED (fixed7), output_calucul, 136, 104);
  gtk_widget_set_size_request (output_calucul, 256, 64);

  calcul_femme = gtk_button_new_with_mnemonic (_("Calcul taux des hommes"));
  gtk_widget_show (calcul_femme);
  gtk_fixed_put (GTK_FIXED (fixed7), calcul_femme, 160, 192);
  gtk_widget_set_size_request (calcul_femme, 184, 56);

  calcul_homme = gtk_button_new_with_mnemonic (_("calculer taux des femmes"));
  gtk_widget_show (calcul_homme);
  gtk_fixed_put (GTK_FIXED (fixed7), calcul_homme, 160, 32);
  gtk_widget_set_size_request (calcul_homme, 192, 56);

  output_fff = gtk_label_new ("");
  gtk_widget_show (output_fff);
  gtk_fixed_put (GTK_FIXED (fixed7), output_fff, 128, 280);
  gtk_widget_set_size_request (output_fff, 248, 64);

  retour_stat_choix = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (retour_stat_choix);
  gtk_fixed_put (GTK_FIXED (fixed7), retour_stat_choix, 160, 368);
  gtk_widget_set_size_request (retour_stat_choix, 176, 54);

  g_signal_connect ((gpointer) calcul_femme, "clicked",
                    G_CALLBACK (on_calcul_femme_clicked),
                    NULL);
  g_signal_connect ((gpointer) calcul_homme, "clicked",
                    G_CALLBACK (on_calcul_homme_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_stat_choix, "clicked",
                    G_CALLBACK (on_retour_stat_choix_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (stat_HF, stat_HF, "stat_HF");
  GLADE_HOOKUP_OBJECT (stat_HF, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (stat_HF, output_calucul, "output_calucul");
  GLADE_HOOKUP_OBJECT (stat_HF, calcul_femme, "calcul_femme");
  GLADE_HOOKUP_OBJECT (stat_HF, calcul_homme, "calcul_homme");
  GLADE_HOOKUP_OBJECT (stat_HF, output_fff, "output_fff");
  GLADE_HOOKUP_OBJECT (stat_HF, retour_stat_choix, "retour_stat_choix");

  return stat_HF;
}

