/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *choix;
  GtkWidget *Ajoutobs;
  GtkWidget *Liste;
  GtkWidget *Supp;
  GtkWidget *Modif;
  GtkWidget *chercher_obser;
GtkWidget *stat_HF;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

 add_pixmap_directory (/*PACKAGE_DATA_DIR "/" PACKAGE*/"../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  choix = create_choix ();
  gtk_widget_show (choix);
	/*chercher_obser = create_chercher_obser();
  gtk_widget_show (chercher_obser);*/

  /*Ajoutobs = create_Ajoutobs ();
  gtk_widget_show (Ajoutobs);*/
  /*Liste = create_Liste ();
  gtk_widget_show (Liste);
  Supp = create_Supp ();
  gtk_widget_show (Supp);
  Modif = create_Modif ();
  gtk_widget_show (Modif);*/

/*stat_HF = create_stat_HF ();
  gtk_widget_show (stat_HF);*/

  gtk_main ();
  return 0;
}

